name: Actions Workfow

on: 
  # push:
    # branches-ingore:   
    # branches:
    #   - master
    #   - 'feature/*' # matches feature/featA, feature/featB, but not feature/feat/a
    #   - 'feature/**' # feature/feat/a
    # tags:
    #tags-ignore:
    #  - v1.*
    # paths:
    #    - '**.js'
    #paths_ignore:
    #  - 'docs/**'

  pull_request:
    types: [closed, assigned, opened, reopened]
  repository_dispatch:
    types: [build]
  # schedule:
  #  - cron: "1 * * * *"

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
          
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
        # the idea to cloning repository by another way
        # git clone git@github:$GITHUB_REPOSITORY
        # git checkout $GITHUB_SHA
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files After Checkout
        run: |
          pwd
          ls
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with: 
          who-to-greet: "Darina Orlova"
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
